<?php

// autoload_namespaces.php @generated by Composer

$vendorDir = dirname(dirname(__FILE__));
$baseDir = dirname($vendorDir);

return array(
    'ebb\\' => array($vendorDir),
    'Whoops' => array($vendorDir . '/filp/whoops/src'),
);
