<?php

// autoload_files.php @generated by Composer

$vendorDir = dirname(dirname(__FILE__));
$baseDir = dirname($vendorDir);

return array(
    $vendorDir . '/ircmaxell/password-compat/lib/password.php',
    $vendorDir . '/admin_function.php',
    $vendorDir . '/function.php',
    $vendorDir . '/posting_function.php',
    $vendorDir . '/template_function.php',
    $vendorDir . '/topic_function.php',
    $vendorDir . '/user_function.php',
);
