<?php

// autoload_classmap.php @generated by Composer

$vendorDir = dirname(dirname(__FILE__));
$baseDir = dirname($vendorDir);

return array(
    'PHPMailer' => $vendorDir . '/PHPMailer/phpmailer/class.phpmailer.php',
    'POP3' => $vendorDir . '/PHPMailer/phpmailer/class.pop3.php',
    'SMTP' => $vendorDir . '/PHPMailer/phpmailer/class.smtp.php',
    'phpmailerException' => $vendorDir . '/PHPMailer/phpmailer/class.phpmailer.php',
);
